### ISSUE TITLE
Please remove AutoGPT-Web-Interaction from your 3rd Party plugin list

### ISSUE THREAD

**Issue by VisionaryMind** [Significant-Gravitas/Auto-GPT-Plugins#169]
[This plugin](https://github.com/gravelBridge/AutoGPT-Web-Interaction) is non-functional, and the developer has demonstrated an unwillingness to understand its issues / fix problems. As stated in [Issue #7](https://github.com/gravelBridge/AutoGPT-Web-Interaction/issues/7) from that repository, the plugin will burn through API credits without ever initiating a valid web hook. It would be best to avoid including such plugins in your list until they have been quality tested, so as to improve user adoption for this platform.

**Comment by gravelBridge** [comment]
You did not install playwright properly, probably because you installed playwright into a different version of Python than the one you use to run AutoGPT. The plugin is functional, myself and several tens of other users use it, and I would recommend browsing the web because this is a common issue, or asking ChatGPT before requesting a whole plugin to be removed.

**Comment by gravelBridge** [comment]
Incredibly, there is even a youtube video showcasing this plugin: https://www.youtube.com/watch?v=iN94Me8IBeU
