### ISSUE TITLE
Error: No such option: --install-plugin-deps

### ISSUE THREAD

**Issue by zenchantlive** [Significant-Gravitas/Auto-GPT-Plugins#75]
Any help with this error code? I seem to be missing the ability to run the python or the run.bat version of step 3 in PowerShell. 

Thanks!

**Comment by Mafyuhh** [comment]
have tried on multiple linux vms and windows, docker and dockerless, still cannot get past this same error

**Comment by askpatrickw** [comment]
This is not supported in Stable.

https://github.com/Significant-Gravitas/Auto-GPT/issues/3353#issuecomment-1524059319

**Comment by zenchantlive** [comment]
So, what should I use then? I am pretty new to this.

**Comment by Observer-Kioskloud** [comment]
Download the master version direct from master branch; https://github.com/Significant-Gravitas/Auto-GPT/tree/master , not its Release section. And then follow the rest of the instruction of the plugin github.
Even though it is not recommended to use master version, autogpt plugins only work on master one.

**Comment by Observer-Kioskloud** [comment]
Download the master version direct from master branch; https://github.com/Significant-Gravitas/Auto-GPT/tree/master , not its Release section. And then follow the rest of the instruction of the plugin github.
Even though it is not recommended to use master version, autogpt plugins only work on master one.

**Comment by askpatrickw** [comment]
> So, what should I use then? I am pretty new to this.

@zenchantlive, You can ask Chat GPT (or any search engine) these things... but I'll get ya going.

When you follow the auto-gpt install steps, you have the stable branch checked out.
You need to checkout the master branch to try out this new feature before it is released and added to the stable branch. Know that master is considered unstable and\or buggy. Since you do not know how to switch branches, you might not want to do this. But you can always switch back, you're not going to break the internet. ;-)

To switch to the master branch:
`git checkout master`
`git pull`

To switch to the stable branch:
`git checkout stable`
`git pull`
